pipeline:
  # Fetch folders from distributed cache
  sftp_cache_restore:
    image: plugins/sftp-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
    when:
      event: [push, pull_request, tag, deployment]

  tests:
    image: scalaplatform/scala:0.6
    commands:
      - sbt test

  publish:
    image: olafurpg/scalafix:0.3.0
    commands:
      - ./bin/ci-publish.sh
    when:
      event: push
      branch: [master]

  # Save folders in distributed cache
  sftp_cache_rebuild:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
