pipeline:
  # Fetch folders from distributed cache
  sftp_cache_restore:
    image: plugins/sftp-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
    when:
      event: [push, pull_request, tag, deployment]

  tests:
    image: scalaplatform/scala:0.6
    commands:
      - sbt ci-test

  publish:
    image: olafurpg/scalafix:0.3.0
    environment:
      - DEPLOY_KEY=$HOME/github_rsa
    commands:
      - echo "$GITHUB_DEPLOY_KEY" > $DEPLOY_KEY
      - chmod 600 $DEPLOY_KEY
      - ssh-agent bash -c "ssh-add $DEPLOY_KEY; sbt -Dsbt.ivy.home=/drone/.ivy2/ readme/publish"
    when:
      event: push
      branch: [master]

  # Save folders in distributed cache
  sftp_cache_rebuild:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
