# Trigger build 8
build:
  image: olafurpg/scalafix:0.0.1
  commands:
    - pip install --user codecov
    - ./bin/testAll.sh
    # I can't be bothered to hide this token.
    - $HOME/.local/bin/codecov -t fffa320c-6875-421f-91a9-5507423edad7

