language: scala
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
git:
  submodules: false
scala:
- 2.11.8
script:
- ./bin/testAll.sh
after_success:
- openssl aes-256-cbc -K $encrypted_3f3a855bcd06_key -iv $encrypted_3f3a855bcd06_iv
  -in deploy_key.enc -out deploy_key -d
- eval `ssh-agent -s`
- ssh-add deploy_key
- ./bin/update-gh-pages.sh
jdk:
- oraclejdk8
notifications:
  email:
  - olafurpg@gmail.com
branches:
  only:
  - master
