language: scala
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
git:
  submodules: false
scala:
- 2.11.8
script:
- ./bin/testAll.sh
jdk:
- oraclejdk8
notifications:
  email:
  - olafurpg@gmail.com
branches:
  only:
  - master
